### ISSUE TITLE
Feedback for "Monitoring and Troubleshooting"

### ISSUE THREAD

**Issue by pfefferf** [SAP-docs/btp-private-link-service#2]
https://help.sap.com/products/PRIVATE_LINK/42acd88cb4134ba2a7d3e0e62c9fe6cf/56fe014a3a8d4d959c071b0ff071355d.html?locale=en-US

When I have an issue with the Private Link service the SAP Cloud Service Status should be checked.
I'm asking myself what service instance(s) should be checked in detail. Should there be a specific one for the Private Link service (which is not there at the moment) or what services will affect the Private Link service?

Thx

**Comment by philipp-becker** [comment]
Good catch! It seems indeed that we're still missing integration into the SAP Cloud Service Status, probably because currently we're still in beta phase. I'll check on the status and can hopefully soon provide an update on when we will be present there as well.

**Comment by gowrisankar22** [comment]
@pfefferf Our help document now has been updated. 
https://help.sap.com/products/PRIVATE_LINK/42acd88cb4134ba2a7d3e0e62c9fe6cf/56fe014a3a8d4d959c071b0ff071355d.html?locale=en-US
